# dial plans

Get-CsTenantDialPlan

#  The global dial plan for your given country is applied along with any tenant level dial plans. Tenant dial plans are applied first, followed by the global dial plan for your country.

$Global = New-Object System.Management.Automation.Host.ChoiceDescription '&Global','Create tenant global dial plan.'
$User = New-Object System.Management.Automation.Host.ChoiceDescription '&User','Create tenant user-level dial plan'

$DPParent = "UK-Non-Geographic"
	New-CsTenantDialPlan $DPParent -Description "Normalization rules for Non-Geographic, United Kingdom`r`n`r`nGenerated by Skype Dialing Rule Optimizer v.13.0 on 2017-Jun-22`r`nCopyright Â© 2017  Ken Lasko (klasko@lyncoptimizer.com)`r`nhttps://skypeoptimizer.com`r`nhttps://ucken.blogspot.com`r`nYou must read and abide by the terms of service at https://skypeoptimizer.com/termsofservice.htm"

$NR = @()
$NR += New-CsVoiceNormalizationRule -Name "UK-Non-Geographic-Local" -Parent $DPParent -Pattern '^(([2-8]\d\d|9[0-8]\d|99[0-8])\d{1,5})$' -Translation '+443$1' -InMemory -Description "Local number normalization for Non-Geographic, United Kingdom`r`n`r`nGenerated by Skype Dialing Rule Optimizer v.13.0 on 2017-Jun-22`r`nCopyright Â© 2017  Ken Lasko (klasko@lyncoptimizer.com)`r`nhttps://skypeoptimizer.com`r`nhttps://ucken.blogspot.com`r`nYou must read and abide by the terms of service at https://skypeoptimizer.com/termsofservice.htm"
$NR += New-CsVoiceNormalizationRule -Name 'UK-TollFree' -Parent $DPParent -Pattern '^0((80(0\d{6,7}|8\d{7}|01111)|500\d{6}))\d*$' -Translation '+44$1' -InMemory -Description "TollFree number normalization for United Kingdom`r`n`r`nGenerated by Skype Dialing Rule Optimizer v.13.0 on 2017-Jun-22`r`nCopyright Â© 2017  Ken Lasko (klasko@lyncoptimizer.com)`r`nhttps://skypeoptimizer.com`r`nhttps://ucken.blogspot.com`r`nYou must read and abide by the terms of service at https://skypeoptimizer.com/termsofservice.htm"
$NR += New-CsVoiceNormalizationRule -Name 'UK-Premium' -Parent $DPParent -Pattern '^0((9[018]\d|87[123]|70\d)\d{7})$' -Translation '+44$1' -InMemory -Description "Premium number normalization for United Kingdom`r`n`r`nGenerated by Skype Dialing Rule Optimizer v.13.0 on 2017-Jun-22`r`nCopyright Â© 2017  Ken Lasko (klasko@lyncoptimizer.com)`r`nhttps://skypeoptimizer.com`r`nhttps://ucken.blogspot.com`r`nYou must read and abide by the terms of service at https://skypeoptimizer.com/termsofservice.htm"
$NR += New-CsVoiceNormalizationRule -Name 'UK-Mobile' -Parent $DPParent -Pattern '^0(7([1-57-9]\d{8}|624\d{6}))$' -Translation '+44$1' -InMemory -Description "Mobile number normalization for United Kingdom`r`n`r`nGenerated by Skype Dialing Rule Optimizer v.13.0 on 2017-Jun-22`r`nCopyright Â© 2017  Ken Lasko (klasko@lyncoptimizer.com)`r`nhttps://skypeoptimizer.com`r`nhttps://ucken.blogspot.com`r`nYou must read and abide by the terms of service at https://skypeoptimizer.com/termsofservice.htm"
$NR += New-CsVoiceNormalizationRule -Name 'UK-National' -Parent $DPParent -Pattern '^0((1[1-9]\d{7,8}|2[03489]\d{8}|3[0347]\d{8}|5[56]\d{8}|8((4[2-5]|70)\d{7}|45464\d)))\d*(\D+\d+)?$' -Translation '+44$1' -InMemory -Description "National number normalization for United Kingdom`r`n`r`nGenerated by Skype Dialing Rule Optimizer v.13.0 on 2017-Jun-22`r`nCopyright Â© 2017  Ken Lasko (klasko@lyncoptimizer.com)`r`nhttps://skypeoptimizer.com`r`nhttps://ucken.blogspot.com`r`nYou must read and abide by the terms of service at https://skypeoptimizer.com/termsofservice.htm"
$NR += New-CsVoiceNormalizationRule -Name 'UK-Service' -Parent $DPParent -Pattern '^(1(47\d|70\d|800\d|1[68]\d{3}|\d\d)|999|[\*\#][\*\#\d]*\#)$' -Translation '$1' -InMemory -Description "Service number normalization for United Kingdom`r`n`r`nGenerated by Skype Dialing Rule Optimizer v.13.0 on 2017-Jun-22`r`nCopyright Â© 2017  Ken Lasko (klasko@lyncoptimizer.com)`r`nhttps://skypeoptimizer.com`r`nhttps://ucken.blogspot.com`r`nYou must read and abide by the terms of service at https://skypeoptimizer.com/termsofservice.htm"
$NR += New-CsVoiceNormalizationRule -Name 'UK-International' -Parent $DPParent -Pattern '^(?:\+|00)(1|7|2[07]|3[0-46]|39\d|4[013-9]|5[1-8]|6[0-6]|8[1246]|9[0-58]|2[1235689]\d|24[013-9]|242\d|3[578]\d|42\d|5[09]\d|6[789]\d|8[035789]\d|9[679]\d)(?:0)?(\d{6,14})(\D+\d+)?$' -Translation '+$1$2' -InMemory -Description "International number normalization for United Kingdom`r`n`r`nGenerated by Skype Dialing Rule Optimizer v.13.0 on 2017-Jun-22`r`nCopyright Â© 2017  Ken Lasko (klasko@lyncoptimizer.com)`r`nhttps://skypeoptimizer.com`r`nhttps://ucken.blogspot.com`r`nYou must read and abide by the terms of service at https://skypeoptimizer.com/termsofservice.htm"

Set-CsTenantDialPlan -Identity $DPParent -NormalizationRules @{add=$NR}


# Good Article from Ken Lasko
#  http://ucken.blogspot.co.uk/2017/04/tenant-dial-plans-in-skype-for-business.html
# 